development:
    display_temperature: true
    display_light: true
    display_power: true
    temperature_units: F
    
test:
    display_temperature: true
    display_light: true
    display_power: true
    temperature_units: F
    
production:
    display_temperature: false
    display_light: false
    display_power: true
    temperature_units: F
    